Add NPM package request as dependency
Without this, We will encounter following errors when run "npm install"
on aglio.

    Loading theme default
    Known data structures: NoteData,NoteList
    Using variables /Users/gasolwu/Code/aglio/node_modules/aglio-theme-olio/styles/variables-default.less
    Using styles /Users/gasolwu/Code/aglio/node_modules/aglio-theme-olio/styles/layout-default.less
    Not cached or out of date. Generating CSS...
      Error: Could not get CSS: Error processing LESS -> CSS: optional
      dependency 'request' required to import over http(s)